"use client"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { cn } from "@/lib/utils"
import { Download, Eye, Layers, Thermometer, X } from "lucide-react"
import Image from "next/image"
import { useState } from "react"

interface DiagnosticDetailViewProps {
  fileName?: string
  onClose: () => void
  analysisResult?: {
    diagnosis: string
    confidence: number
    original_image: string
    segmentation_mask: string
    grad_cam_heatmap: string
    shap_values: Record<string, number>
    midnight_proof_hash: string
  }
}

export function DiagnosticDetailView({ fileName, onClose, analysisResult }: DiagnosticDetailViewProps) {
  const [overlayMode, setOverlayMode] = useState<"none" | "mask" | "heatmap">("none")

  // Helper to get the correct image based on overlay mode
  const getDisplayImage = () => {
    if (!analysisResult) return "/placeholder.svg"
    
    switch (overlayMode) {
      case "none":
        return analysisResult.original_image
      case "mask":
        return analysisResult.segmentation_mask
      case "heatmap":
        return analysisResult.grad_cam_heatmap
      default:
        return analysisResult.original_image
    }
  }

  // Download Report Function
  const handleDownloadReport = () => {
    if (!analysisResult) return

    const reportContent = `
AURA MEDICAL IMAGING ANALYSIS REPORT
=====================================

Patient File: ${fileName || "Unknown"}
Analysis Date: ${new Date().toLocaleString()}

DIAGNOSIS
---------
${analysisResult.diagnosis}
Confidence: ${(analysisResult.confidence * 100).toFixed(1)}%

FEATURE IMPORTANCE (SHAP Values)
---------------------------------
${Object.entries(analysisResult.shap_values)
  .map(([key, value]) => `${key}: ${value.toFixed(3)}`)
  .join('\n')}

PRIVACY VERIFICATION
--------------------
Midnight Proof Hash: ${analysisResult.midnight_proof_hash}

BLOCKCHAIN VERIFICATION
-----------------------
This analysis has been cryptographically verified on the Cardano blockchain.
The patient's medical data remains private using Midnight zero-knowledge proofs.

---
Generated by Aura MedSAM Platform
Powered by Cardano & Midnight Privacy
    `.trim()

    // Create blob and download
    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `aura-report-${fileName || 'analysis'}-${Date.now()}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)

    console.log("📄 Report Downloaded")
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm">
      <div className="container mx-auto h-full p-6 flex items-center justify-center">
        <Card className="w-full max-w-7xl h-[90vh] bg-slate-900 border-slate-700 overflow-hidden">
          <div className="h-full flex flex-col">
            {/* Header */}
            <div className="p-6 border-b border-slate-700 flex items-center justify-between">
              <div>
                <h2 className="text-2xl font-bold text-white">Analysis Results</h2>
                <p className="text-slate-400 text-sm mt-1">{fileName || "Medical Image"}</p>
              </div>
              <Button variant="ghost" size="icon" onClick={onClose}>
                <X className="h-5 w-5" />
              </Button>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-auto p-6">
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Left: Image Viewer */}
                <div className="lg:col-span-2 space-y-4">
                  {/* Overlay Controls */}
                  <div className="flex gap-2">
                    <Button
                      variant={overlayMode === "none" ? "default" : "outline"}
                      size="sm"
                      onClick={() => setOverlayMode("none")}
                      className={cn(
                        overlayMode === "none" && "bg-cyan-500 hover:bg-cyan-600 text-white"
                      )}
                    >
                      <Eye className="h-4 w-4 mr-2" />
                      Original
                    </Button>
                    <Button
                      variant={overlayMode === "mask" ? "default" : "outline"}
                      size="sm"
                      onClick={() => setOverlayMode("mask")}
                      className={cn(
                        overlayMode === "mask" && "bg-purple-500 hover:bg-purple-600 text-white"
                      )}
                    >
                      <Layers className="h-4 w-4 mr-2" />
                      Mask
                    </Button>
                    <Button
                      variant={overlayMode === "heatmap" ? "default" : "outline"}
                      size="sm"
                      onClick={() => setOverlayMode("heatmap")}
                      className={cn(
                        overlayMode === "heatmap" && "bg-orange-500 hover:bg-orange-600 text-white"
                      )}
                    >
                      <Thermometer className="h-4 w-4 mr-2" />
                      Heatmap
                    </Button>
                  </div>

                  {/* Image Display */}
                  <Card className="bg-black/50 border-slate-700 aspect-square relative overflow-hidden">
                    <Image
                      src={getDisplayImage()}
                      alt="Medical Scan"
                      fill
                      className="object-contain"
                      unoptimized
                    />
                  </Card>
                </div>

                {/* Right: Analysis Details */}
                <div className="space-y-4">
                  {/* Diagnosis Card */}
                  <Card className="p-4 bg-slate-800 border-slate-700">
                    <h3 className="text-sm font-medium text-slate-400 mb-2">Diagnosis</h3>
                    <p className="text-lg font-bold text-white mb-3">
                      {analysisResult?.diagnosis || "Processing..."}
                    </p>
                    <div className="flex items-center gap-2">
                      <span className="text-sm text-slate-400">Confidence:</span>
                      <Badge variant="outline" className="bg-green-500/10 text-green-400 border-green-500/50">
                        {analysisResult ? `${(analysisResult.confidence * 100).toFixed(1)}%` : "—"}
                      </Badge>
                    </div>
                  </Card>

                  {/* SHAP Values Card */}
                  <Card className="p-4 bg-slate-800 border-slate-700">
                    <h3 className="text-sm font-medium text-slate-400 mb-3">Feature Importance</h3>
                    <div className="space-y-3">
                      {analysisResult?.shap_values ? (
                        Object.entries(analysisResult.shap_values).map(([feature, value]) => (
                          <div key={feature} className="space-y-1">
                            <div className="flex justify-between text-sm">
                              <span className="text-slate-300 capitalize">
                                {feature.replace(/_/g, ' ')}
                              </span>
                              <span className="text-cyan-400 font-mono">
                                {typeof value === 'number' ? value.toFixed(3) : value}
                              </span>
                            </div>
                            <div className="h-2 bg-slate-700 rounded-full overflow-hidden">
                              <div
                                className="h-full bg-gradient-to-r from-cyan-500 to-blue-500 rounded-full transition-all"
                                style={{ 
                                  width: `${typeof value === 'number' ? Math.abs(value) * 100 : 0}%` 
                                }}
                              />
                            </div>
                          </div>
                        ))
                      ) : (
                        <p className="text-slate-500 text-sm">No data available</p>
                      )}
                    </div>
                  </Card>

                  {/* Privacy Proof Card */}
                  <Card className="p-4 bg-slate-800 border-slate-700">
                    <h3 className="text-sm font-medium text-slate-400 mb-2">Privacy Proof</h3>
                    <p className="text-xs text-slate-500 font-mono break-all">
                      {analysisResult?.midnight_proof_hash || "Not available"}
                    </p>
                  </Card>

                  {/* Download Button */}
                  <Button 
                    className="w-full bg-cyan-500 hover:bg-cyan-600 text-white"
                    onClick={handleDownloadReport}
                    disabled={!analysisResult}
                  >
                    <Download className="h-4 w-4 mr-2" />
                    Download Report
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </Card>
      </div>
    </div>
  )
}